/** a collection of taglines for the index page */
pub static TAGS: &[&str] = &[
    "haven for the huddled masses",
    "padded cell for autistic transexuals",
    "im whatever you want me to be baby",
    "who are you, man?",
    "what lol",
    "SHUT THE FUCK UP",
    "powered by manic psychosis",
    "powered by delusions of grandeur",
    "powered by a 2015 DELL PC",
    "powered by illumos",
    "powered by monster energy and cigarettes",
    "you didn't see shit",
    "this website is a product of your imagination",
    "you don't know me",
    "whatever hoe",
    "insane asylum",
    "we don't want your bitch ass",
    "lesbian slut heaven",
    "party doll club",
    "gauche and pedestrian",
    "intellectuals and computer scientists",
    "you wouldn't get it anyway",
    "powered by sqlite",
    "who fucking cares",
    "nothing is nothing brah",
    "banned in the UK",
    "banned for pornography",
    "uhh",
    "why",
    "heavily optimized",
    "masked by optimism",
    "childfree",
    "everyone's favorite",
    "im 12",
    "WARNING: incest",
    "WARNING: gay people",
    "WARNING: gay incest",
    "XXX",
    "COMPUT3R H4X0RS",
    "just say you hate me",
    "women are inevitable",
    "running smuggled geek bars",
    "written in rust",
    "hehe",
    "ROFL",
    ":3",
    "furries and other such degenerates",
    "hh",
    "BRUH",
    "faggots ONLY",
    "speed demons",
    "fast and furious",
    "dry humping",
    "OK",
    "cool, bro",
    "we are young and turnt transexuals",
    "stealing your car stereo",
    "got a dip",
    "can i bum a cig",
    "chuffing darts",
    "an actual cult",
    "i love my wife",
    "hypersexual since 2016",
    "im surrounded by philistines",
    "drugs, sex, and rock & roll",
    "goooood stuff man",
    "part-time weed dealers",
];

/** get a random tag out of TAGS */
#[inline(always)]
pub fn tag() -> &'static str {
    let L = TAGS.len() as u16;
    let i = rand::random::<u16>() % L;
    TAGS[i as usize]
}
